### ISSUE TITLE
Upgraded Omada Controller and Omada Exporter - Exporter No Longer Runs

### ISSUE THREAD

**Issue by RichieRogers** [charlie-haley/omada_exporter#95] opened 2024-06-12 09:53 UTC
Hi,
I've just upgraded my Omada Controller to version 5.14.20.9 and exporter to v0.13.0.
However, I now get the following error when trying to run the exporter:
sudo /bin/omada-exporter --host https://my-omada-server:8043 --username prometheus --password REDACTED --insecure true

panic: runtime error: slice bounds out of range [1:0]

goroutine 1 [running]:
github.com/charlie-haley/omada_exporter/pkg/api.(*Client).getCid(0x40000b2680)
        github.com/charlie-haley/omada_exporter@v0.13.0/pkg/api/auth.go:64 +0x1a4
github.com/charlie-haley/omada_exporter/pkg/api.Configure(0x8dd660)
        github.com/charlie-haley/omada_exporter@v0.13.0/pkg/api/api.go:51 +0x88
github.com/charlie-haley/omada_exporter/cmd.run(0x44b9a0?)
        github.com/charlie-haley/omada_exporter@v0.13.0/cmd/exporter.go:91 +0x19c
github.com/urfave/cli/v2.(*App).RunContext(0x4000082680, {0x5bda68?, 0x4000120020}, {0x4000128000, 0x9, 0x9})
        github.com/urfave/cli/v2@v2.3.0/app.go:322 +0x6ec
github.com/urfave/cli/v2.(*App).Run(...)
        github.com/urfave/cli/v2@v2.3.0/app.go:224
github.com/charlie-haley/omada_exporter/cmd.Run()
        github.com/charlie-haley/omada_exporter@v0.13.0/cmd/exporter.go:60 +0xca4
main.main()
        github.com/charlie-haley/omada_exporter@v0.13.0/main.go:8 +0x1c

Is there a fix for this?

Thanks,
Richie

**Comment by jasonhouston** [comment] 2024-07-05 21:18
I'm getting the same errors, though interestingly this only started after the last reboot of my Omada controller yesterday.  Before that, it had been working.

**Comment by tukane** [comment] 2024-07-07 14:50
Same here.

**Comment by codersaur** [comment] 2024-07-11 18:59
and here

**Comment by chjohans** [comment] 2024-07-13 11:41
I'm getting the same error, was driving me nuts until I found this. I did make some changes on the server that was running this docker image, and I thought it was somehow related to that, even if it should not cause this. This is a very useful collector so hopefully, @charlie-haley will have a look at and eventually fix this.

**Comment by mixman68** [comment] 2024-07-20 23:01
I see the problem, the redirect from / to /cid/login doesn't exist anymore, the login is made here,

I forked the repo and added CID param.

I think pass to OpenAPI of Omada is better to avoid futures issues

**Comment by RichieRogers** [comment] 2024-07-21 20:00
@mixman68 Great you have a fix.
Sadly I have no idea how to compile this into an arm64 deb package I can put onto my Raspberry Pi - any docs on this?

Thanks,
Richie

**Comment by mixman68** [comment] 2024-07-21 20:39
Hello, it's programmed in golang

so no necessity of .deb, for mine I compile with this command

`GOOS=linux GOARCH=arm64 go build -o omada-exporter`

after this you get a single executable with all included to run without dependencies

**Comment by tukane** [comment] 2024-07-22 05:42
But I can also wait until the fix is included in a new version of the docker file, right?

**Comment by charlie-haley** [comment] 2024-07-22 07:38
Hi, thanks for raising this! I should have some time this week to investigate what's exactly happened here, in the meantime I'd recommend not upgrading until a fix has been released

**Comment by blesswinsamuel** [comment] 2024-08-04 21:41
I [made a fix](https://github.com/charlie-haley/omada_exporter/pull/96) by taking ideas from [the ha-omada integration](https://github.com/zachcheatham/ha-omada/blob/65b267e3c3718a35d71e184f9d2538b26dadf751/custom_components/omada/api/controller.py#L56-L79). I tested it on 5.14.26.1, don't know if it will break older versions.

For anyone impatient who want to try it out, I pushed a docker image here - https://github.com/blesswinsamuel/omada_exporter/pkgs/container/omada_exporter (`ghcr.io/blesswinsamuel/omada_exporter:0.0.3`).

**Comment by franzfopa** [comment] 2024-08-05 01:34
> I [made a fix](https://github.com/charlie-haley/omada_exporter/pull/96) by taking ideas from [the ha-omada integration](https://github.com/zachcheatham/ha-omada/blob/65b267e3c3718a35d71e184f9d2538b26dadf751/custom_components/omada/api/controller.py#L56-L79). I tested it on 5.14.26.1, don't know if it will break older versions.
> 
> For anyone wants to try it out, I pushed a docker image here - https://github.com/blesswinsamuel/omada_exporter/pkgs/container/omada_exporter (`ghcr.io/blesswinsamuel/omada_exporter:0.0.3`).

confirmed working on 5.14.26.1 - seems like all is working via docker compose.

**Comment by jasonhouston** [comment] 2024-08-05 17:04
Confirmed on 5.14.26.1 for me as well

> I [made a fix](https://github.com/charlie-haley/omada_exporter/pull/96) by taking ideas from [the ha-omada integration](https://github.com/zachcheatham/ha-omada/blob/65b267e3c3718a35d71e184f9d2538b26dadf751/custom_components/omada/api/controller.py#L56-L79). I tested it on 5.14.26.1, don't know if it will break older versions.
> 
> For anyone wants to try it out, I pushed a docker image here - https://github.com/blesswinsamuel/omada_exporter/pkgs/container/omada_exporter (`ghcr.io/blesswinsamuel/omada_exporter:0.0.3`).

**Comment by charlie-haley** [comment] 2024-08-05 17:57
Thanks for the PR @blesswinsamuel! It looks like the OpenAPI integration is working now too, I'll look at building a client from there now which will hopefully avoid issues like this going forward. Thank you everyone for your patience!

**Closed** 2024-08-05 18:08 UTC

**Comment by RichieRogers** [comment] 2024-08-05 18:34
Hi, 
0.13.1 of the omada exporter works.
Thanks for fixing.

Much appreciated,
Richie

**Comment by RichieRogers** [comment] 2024-08-26 13:30
Hi,
Sorry to re-open this one, but any chance of updating the Helm chart to use the new version?
I'm migrating over to Kubernetes and this error has popped up again.

Many Thanks,
Richie
